### ISSUE TITLE
我遇到一个不能连接的问题

### ISSUE THREAD

**Issue by linkerlin** [blakey22/shadowsocks-java#1]
编译最新代码后，运行得到如下的错误提示：

2015-Dec-15 22:44:54 [INFO] Shadowsocks-Java v0.1
2015-Dec-15 22:44:54 [INFO] Server starts at port: 1080
2015-Dec-15 22:44:59 [INFO] Connected to:
2015-Dec-15 22:44:59 [INFO] Connected to:
2015-Dec-15 22:44:59 [INFO] Connected to: 0.0.0.0:0
2015-Dec-15 22:45:00 [INFO] Connected to:
2015-Dec-15 22:45:00 [INFO] Connected to: -74.-2.12.-105:80
2015-Dec-15 22:45:00 [INFO] Connected to:
2015-Dec-15 22:45:00 [INFO] Connected to:
2015-Dec-15 22:45:00 [INFO] Connected to: -74.-2.12.-105:80
2015-Dec-15 22:45:01 [INFO] Connected to:
2015-Dec-15 22:45:01 [INFO] Connected to:
2015-Dec-15 22:45:01 [INFO] Connected to: -74.-2.12.-105:80
2015-Dec-15 22:45:01 [INFO] Connected to: -74.-2.12.-105:80
2015-Dec-15 22:45:04 [INFO] Connected to:
2015-Dec-15 22:45:04 [INFO] Connected to:
2015-Dec-15 22:45:05 [INFO] Connected to:
2015-Dec-15 22:45:05 [INFO] Connected to: 0.0.0.0:0
2015-Dec-15 22:45:06 [INFO] Connected to:
2015-Dec-15 22:45:06 [INFO] Connected to: -37.-23.31.87:80
2015-Dec-15 22:45:06 [INFO] Connected to:
2015-Dec-15 22:45:06 [INFO] Connected to:
2015-Dec-15 22:45:06 [INFO] Connected to:
2015-Dec-15 22:45:06 [INFO] Connected to:
2015-Dec-15 22:45:06 [INFO] Connected to:
2015-Dec-15 22:45:06 [INFO] Connected to:
2015-Dec-15 22:45:06 [INFO] Connected to:
2015-Dec-15 22:45:07 [INFO] Connected to:
2015-Dec-15 22:45:07 [INFO] Connected to:
2015-Dec-15 22:45:07 [INFO] Connected to:
2015-Dec-15 22:45:07 [INFO] Connected to:
2015-Dec-15 22:45:07 [INFO] Connected to:
2015-Dec-15 22:45:07 [INFO] Connected to:
2015-Dec-15 22:45:07 [INFO] Connected to:
2015-Dec-15 22:45:07 [INFO] Connected to:
2015-Dec-15 22:45:07 [INFO] Connected to: -74.-2.12.-105:80
2015-Dec-15 22:45:07 [INFO] Connected to:
2015-Dec-15 22:45:07 [INFO] Connected to: -74.-2.12.-105:80
2015-Dec-15 22:45:08 [INFO] Connected to:
2015-Dec-15 22:45:08 [INFO] Connected to:
2015-Dec-15 22:45:08 [INFO] Connected to: -74.-2.12.-105:80
2015-Dec-15 22:45:08 [INFO] Connected to: -74.-2.12.-105:80
2015-Dec-15 22:45:08 [INFO] Connected to:
2015-Dec-15 22:45:08 [INFO] Connected to:
2015-Dec-15 22:45:08 [INFO] Connected to:
2015-Dec-15 22:45:08 [INFO] Connected to:
2015-Dec-15 22:45:08 [INFO] Connected to:
2015-Dec-15 22:45:08 [INFO] Connected to:
2015-Dec-15 22:45:08 [INFO] Connected to:
2015-Dec-15 22:45:09 [INFO] Connected to:
2015-Dec-15 22:45:09 [INFO] Connected to:
2015-Dec-15 22:45:09 [INFO] Connected to: -74.-2.12.-105:80
2015-Dec-15 22:45:09 [INFO] Connected to: -74.-2.12.-105:80
2015-Dec-15 22:45:09 [INFO] Connected to:
2015-Dec-15 22:45:09 [INFO] Connected to: -74.-2.12.-105:80
2015-Dec-15 22:45:10 [INFO] Connected to:
2015-Dec-15 22:45:10 [INFO] Connected to: -74.-2.12.-105:80
2015-Dec-15 22:45:10 [INFO] Connected to:
2015-Dec-15 22:45:10 [INFO] Connected to: 0.0.0.0:0
2015-Dec-15 22:45:11 [INFO] Connected to:
2015-Dec-15 22:45:12 [INFO] Connected to:
2015-Dec-15 22:45:12 [INFO] Connected to: -37.-23.31.87:80
2015-Dec-15 22:45:12 [INFO] Connected to:
2015-Dec-15 22:45:12 [INFO] Connected to: -37.-23.31.87:80

**Comment by blakey22** [comment]
剛剛更新了代碼，修正了一些連接上的 bug, 不過這個版本還不支持 shadowsocks-SSR

**Comment by linkerlin** [comment]
谢谢！
