### ISSUE TITLE
mac上启动OK，但是代理不了

### ISSUE THREAD

**Issue by koywang** [blakey22/shadowsocks-java#7]
如题！！

**Comment by koywang** [comment]
剛剛在windows也試了下，也是啟動正常，翻墻失敗！！shadowsocks官方版本的可以！！
測試賬號來源：http://www.ishadowsocks.org/#free

**Comment by ksfzhaohui** [comment]
用netty实现了一个https://github.com/ksfzhaohui/shadowsocks-netty
